config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # Defining root depending on whether logged in or not
  unauthenticated do
    root 'pages#home'
  end
  authenticated do
    root 'pages#call_facebook'
  end

  get '/redirect', to: 'pages#redirect', as: 'redirect'

  # GROUPS CONTROLLERS
  resources :groups, only: [:show, :update, :destroy]
  get '/new_kitty', to: 'groups#new_kitty', as: 'new_group'
  get '/reminder', to: 'groups#reminder', as: 'groups_reminder'

  # USERS CONTROLLERS
  resources :users, only: [:show]
  get '/transactions/:id', to: 'users#transactions', as: 'user_transactions'
  get '/friends/:id', to: 'users#friends', as: 'user_friends'
  get '/dashboard/:id', to: 'users#dashboard', as: 'user_dashboard'
  get '/settle_all', to: 'users#settle_all', as: 'user_settle_all'

  # EXPENSES CONTROLLERS
  resources :expenses, only: [:new, :create, :show]
  post '/expenses/upload', to: 'expenses#upload', as: 'expenses_upload'

  # WEBHOOKS CONTROLLER
  get 'webhooks', to: 'webhooks#messenger'
  post 'webhooks', to: 'webhooks#messenger_receive_message'

  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :create ]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :memberships
  has_many :groups, through: :memberships
  has_many :expenses
  has_many :splits

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.image = auth.info.image
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.gender = auth.extra.raw_info.gender
      user.age_range_minimum = auth.extra.raw_info.age_range.min[1]
      user.locale = auth.extra.raw_info.locale
      user.timezone = auth.extra.raw_info.timezone
    end
  end

  def outstanding_with_person_in_group(comparison_user, group)
    user_owed_splits = Split.joins(:expense).where(expenses: {user_id: self.id}).where(user_id: comparison_user.id).where(expenses: {group_id: group.id})
    user_owes_splits = Split.joins(:expense).where(expenses: {user_id: comparison_user.id}).where(user_id: self.id).where(expenses: {group_id: group.id})

    currency = self.preferred_currency

    user_owes_total = Money.new(0, currency)
    user_owed_total = Money.new(0, currency)

    user_owed_splits.each do |split|
      if split.amount_currency == currency
        user_owed_total += split.amount
      else
        exchange_rate_object = ExchangeRate.find_by(id: split.expense.exchange_rates_id)
        exchange_rate = exchange_rate_object[:rates][currency]
        Money.add_rate(split.amount_currency, currency, exchange_rate)
        split_amount_in_preferred_currency = split.amount.exchange_to(currency)
        user_owed_total += split_amount_in_preferred_currency
      end
    end

    user_owes_splits.each do |split|
      if split.amount_currency == currency
        user_owes_total += split.amount
      else
        exchange_rate_object = ExchangeRate.find_by(id: split.expense.exchange_rates_id)
        exchange_rate = exchange_rate_object[:rates][currency]
        Money.add_rate(split.amount_currency, currency, exchange_rate)
        split_amount_in_preferred_currency = split.amount.exchange_to(currency)
        user_owes_total += split_amount_in_preferred_currency
      end
    end

    return user_owed_total - user_owes_total
  end

  def outstanding_with_person_overall(comparison_user)
    user_owed_splits = Split.joins(:expense).where(expenses: {user_id: self.id}).where(user_id: comparison_user.id)
    user_owes_splits = Split.joins(:expense).where(expenses: {user_id: comparison_user.id}).where(user_id: self.id)

    currency = self.preferred_currency

    user_owes_total = Money.new(0, currency)
    user_owed_total = Money.new(0, currency)

    user_owed_splits.each do |split|
      if split.amount_currency == currency
        user_owed_total += split.amount
      else
        exchange_rate_object = ExchangeRate.find_by(id: split.expense.exchange_rates_id)
        exchange_rate = exchange_rate_object[:rates][currency]
        Money.add_rate(split.amount_currency, currency, exchange_rate)
        split_amount_in_preferred_currency = split.amount.exchange_to(currency)
        user_owed_total += split_amount_in_preferred_currency
      end
    end

    user_owes_splits.each do |split|
      if split.amount_currency == currency
        user_owes_total += split.amount
      else
        exchange_rate_object = ExchangeRate.find_by(id: split.expense.exchange_rates_id)
        exchange_rate = exchange_rate_object[:rates][currency]
        Money.add_rate(split.amount_currency, currency, exchange_rate)
        split_amount_in_preferred_currency = split.amount.exchange_to(currency)
        user_owes_total += split_amount_in_preferred_currency
      end
    end

    return user_owed_total - user_owes_total
  end

  def outstanding_with_group(group)
    user_owes_splits = Split.joins(:expense).where(user_id: self.id).where(expenses: {group_id: group.id})
    user_owed_splits = Split.joins(:expense).where(expenses: {user_id: self.id}).where(expenses: {group_id: group.id})

    currency = self.preferred_currency

    user_owes_total = Money.new(0, currency)
    user_owed_total = Money.new(0, currency)

    user_owed_splits.each do |split|
      if split.amount_currency == currency
        user_owed_total += split.amount
      else
        exchange_rate_object = ExchangeRate.find_by(id: split.expense.exchange_rates_id)
        exchange_rate = exchange_rate_object[:rates][currency]
        Money.add_rate(split.amount_currency, currency, exchange_rate)
        split_amount_in_preferred_currency = split.amount.exchange_to(currency)
        user_owed_total += split_amount_in_preferred_currency
      end
    end

    user_owes_splits.each do |split|
      if split.amount_currency == currency
        user_owes_total += split.amount
      else
        exchange_rate_object = ExchangeRate.find_by(id: split.expense.exchange_rates_id)
        exchange_rate = exchange_rate_object[:rates][currency]
        Money.add_rate(split.amount_currency, currency, exchange_rate)
        split_amount_in_preferred_currency = split.amount.exchange_to(currency)
        user_owes_total += split_amount_in_preferred_currency
      end
    end

    return user_owed_total - user_owes_total
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  def create
    puts "...."
    encoded_sig, payload = get_params[:signed_request].split(".")
    sig = encoded_sig.tr('-_','+/').unpack('m')[0]
    expected_sig = OpenSSL::HMAC.digest(OpenSSL::Digest.new('sha256'), ENV['APP_SECRET'], payload)
    puts "All ok re signature"
    # Renders a JSON with the URL to be redirected to in the pages/redirect view Javascript
    url = Rails.application.routes.url_helpers.redirect_url(tid: get_params[:tid], thread_type: get_params[:thread_type])
    puts url
    render json: {url: url}, status: :created
  end

  # SUPPORTER PRIVATE METHODS
  private

  def choosing_non_bot_redirect(user, group)
    if group
      if group.closed
        puts "5. The group exists, but has been closed. Need to rerun creata kitty."
        url = create_kitty_url(user, group)
      elsif group.kitty_created
        url = first_sign_in_url(user, group)
      else
        puts "5. The group exists, but they have not created a kitty yet."
        url = create_kitty_url(group)
      end
    else
      puts "5. This is a new group. Creating Group..."
      group = Group.create(tid: get_params[:tid], name: "Your Kitty", thread_type: get_params[:thread_type])
      url = create_kitty_url(user, group)
    end
    return url
  end

  def first_sign_in_url(user, group)
    if user.first_sign_in
      puts "5. This is the user's first sign in. Group Already Exists"
      # user.first_sign_in = false
      # user.save
      # url = Rails.application.routes.url_helpers.info_url(user_id: user.id, group_id: group.id)
      url = Rails.application.routes.url_helpers.group_url(group, user_id: user.id, group_id: group.id)
      return url
    else
      puts "5. This is not the user's first sign in. Group Already Exists"
      url = Rails.application.routes.url_helpers.group_url(group, user_id: user.id, group_id: group.id)
      return url
    end
  end

  def create_kitty_url(group)
    url = Rails.application.routes.url_helpers.new_group_url(group, group_id: group.id)
  end

  def get_params
    params.require(:user).permit(:psid, :tid, :thread_type, :signed_request)
  end

  def get_user_id
    params.require(:signed_in_id).permit(:user_id)
  end

  def render_error
    render json: { errors: @user.errors.full_messages },
      status: :unprocessable_entity
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    auth = request.env["omniauth.auth"]
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @hidenav = false
    @hidebtn = false

    @user = current_user
    @group = current_group
    @profile_owner = User.find(params[:id])

    @balance = get_user_balance(@profile_owner)
    @expenses_paid = Expense.where(user_id: @profile_owner.id)
    @amount_lent = amount_lent(@expenses_paid)
    @splits_owed = Split.where(user_id: @profile_owner.id)
    @amount_borrowed = amount_borrowed(@splits_owed)
  end

  def transactions
    @hidebtn = false
    @hidenav = false
    @tabs = ["Group", "All"]

    @user = current_user
    @group = current_group
    @transactions = all_user_transactions(@user)
    @transaction_dates = get_all_dates_transacted_upon(@transactions)
    @in_group_transactions = filter_transactions_for_group(@transactions, @group)
    @in_group_transaction_dates = get_all_dates_transacted_upon_in_group(@in_group_transactions)
  end

  def friends
    @hidebtn = false
    @hidenav = false

    @user = current_user
    @group = current_group
    @users = User.all
    @friends = get_users_friends(@user)

    # @users_user_owed_by = users_user_owed_by(@user, @users)
    # @users_user_owes = users_user_owes(@user, @users)
    #
    # if @users_user_owed_by.length == 0 && @users_user_owes.length == 0
    #   render 'owes_and_owed_by_no_one'
    # end
  end

  def dashboard
    @hidebtn = false
    @hidenav = false
    @tabs = ["Details", "Groups"]

    @user = current_user
    @group = current_group
    @users = User.all

    @expenses_paid = Expense.where(user_id: @user.id)
    @amount_lent = amount_lent(@expenses_paid)
    @splits_owed = Split.where(user_id: @user.id)
    @amount_borrowed = amount_borrowed(@splits_owed)
    @users_user_owed_by = users_user_owed_by(@user, @users)
    @users_user_owes = users_user_owes(@user, @users)
    @transactions = all_user_transactions(@user)
    @balance = get_user_balance(@user)
  end

  def settle_all
    @hidebtn = true
    @hidenav = true

    @user = current_user
    @group = current_group
    @settle_with_user = User.find(params["settle_with_id"])

    settle_up_in_each_group(@user, @settle_with_user)
    redirect_to user_friends_path(@user)
  end

  private

  def get_users_friends(user)
    friends = []
    user.groups.each do |group|
      group.users.each do |member|
        friends << member
      end
    end
    p friends.uniq.sort { |a,b| a.first_name.downcase <=> b.first_name.downcase }
  end

  def settle_up_in_each_group(user, settle_with_user)
    user_groups = Group.joins(:memberships).where(memberships: {user_id: user.id})
    settle_with_user_groups = Group.joins(:memberships).where(memberships: {user_id: settle_with_user.id})
    shared_groups = []

    user_groups.each do |group|
      if group.users.include?(settle_with_user)
        shared_groups << group
      end
    end
    settle_with_user_groups.each do |group|
      if group.users.include?(settle_with_user)
        shared_groups << group
      end
    end

    shared_groups.uniq.each do |group|
      amount_pennies = (user.outstanding_with_person_in_group(settle_with_user, group) * -1).fractional
      amount_currency = (user.outstanding_with_person_in_group(settle_with_user, group) * -1).currency.iso_code

      expense = Expense.new(
          title: "#{user.first_name} settled up with #{settle_with_user.first_name}",
          description: "Settled",
          amount_pennies: amount_pennies,
          amount_currency: amount_currency,
          amount: Money.new(amount_pennies, amount_currency),
          user_id: user.id,
          group_id: group.id,
          location: "",
          payment_method: "card")
      expense.exchange_rates_id = ExchangeRate.where(base: amount_currency).last.id

      if expense.save
        split = Split.new(expense_id: expense.id,
          user_id: settle_with_user.id,
          amount_pennies: expense.amount_pennies,
          amount_currency: expense.amount_currency,
          amount: Money.new(expense.amount_pennies, expense.amount_currency))

        split.save!
      end
    end
  end

  def all_user_transactions(user)
    transactions = []
    expenses_paid = Expense.where(user_id: user.id)
    p expenses_paid
    splits_owed = Split.where(user_id: user.id)
    p splits_owed

    expenses_paid.each do |expense|
      transactions << expense
    end
    splits_owed.each do |split|
      transactions << split
    end
    return transactions.sort_by { |item| item.created_at }.reverse
  end

  def filter_transactions_for_group(transactions, group)
    filtered_transactions = []
    unless group == "no_group"
      transactions.each do |transaction|
        if transaction.group.id == group.id
          filtered_transactions << transaction
        end
      end
    end
    return filtered_transactions
  end

  def get_all_dates_transacted_upon(transactions)
    dates = []
    transactions.each do |transaction|
      dates << transaction.created_at.strftime("%d/%m/%Y")
    end
    p dates.uniq
    return dates.uniq
  end

  def get_all_dates_transacted_upon_in_group(transactions)
    dates = []
    transactions.each do |transaction|
      dates << transaction.created_at.strftime("%d/%m/%Y")
    end
    p dates.uniq
    return dates.uniq
  end

  def get_user_balance(user)
    balance_cents = 0
    user.groups.each do |group|
      balance_cents += user.outstanding_with_group(group)
    end
    return balance_cents
  end

  def amount_lent(expenses_paid)
    amount_lent = 0
    expenses_paid.each do |expense|
      amount_lent += expense.amount_pennies
    end
    return amount_lent
  end

  def amount_borrowed(splits_owed)
    amount_borrowed = 0
    splits_owed.each do |split|
      amount_borrowed += split.amount_pennies
    end
    return amount_borrowed
  end

  def users_user_owed_by(current_user, users)
    users_owed = []
    users.each do |user|
      if current_user.outstanding_with_person_overall(user) > 0
        users_owed << user
      end
    end
    return users_owed
  end

  def users_user_owes(current_user, users)
    users_owes = []
    users.each do |user|
      if current_user.outstanding_with_person_overall(user) < 0
        users_owes << user
      end
    end
    return users_owes
  end
end

app/views/users/friends.html.erb
<div class="container">
  <div class="title-section">
    <h3>Friends</h3>
  </div>

  <% @friends.each do |member| %>
    <% next if member == @user %>
    <%= link_to user_path(member) do %>
      <div class="list-item-tall">
        <div class="profile-img-container">
          <%= image_tag member.image + "?type=normal", class: "avatar-medium" %>
        </div>
        <div class="divider">
          <div class="list-item-divider-content">
            <p class="list-item-text"><strong><%= member.first_name %> <%= member.last_name %></strong></p>
            <% if @user.outstanding_with_person_overall(member) == 0 %>
              <p class="list-item-text" >All square</p>
            <% elsif @user.outstanding_with_person_overall(member) < 0 %>
              <p class="list-item-text" >You owe: <span class="color-danger"> <%= humanized_money_with_symbol (@user.outstanding_with_person_overall(member) * -1) %></span></p>
            <% else %>
              <p class="list-item-text">Owes you: <span class="color-primary"><%= humanized_money_with_symbol @user.outstanding_with_person_overall(member) %></span></p>
            <% end %>
          </div>
          <div class="list-item-arrow-btn">
              <p class="list-item-text" ><i class="fa fa-arrow-right" aria-hidden="true"></i></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/owes_and_owed_by_no_one.html.erb
<div class="container">
  <div class="plain-card-content-center-vertical-max-height">
    <div class="text-center">
      <h3>Looks like you and your friends have no outstanding expenses...</h3>
      <p>Good work! Although, maybe you just aren't using Kitty enough.</p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-header text-center">
  <%= image_tag @profile_owner.image + "?type=large", class: "avatar-profile-picture" %>
  <h2 class="color-white"><%= @profile_owner.first_name %> <%= @profile_owner.last_name %></h2>
  <% if @profile_owner != @user %>
    <% if @user.outstanding_with_person_overall(@profile_owner) < 0 %>
      <h4 class="color-white">You owe them: <%= humanized_money_with_symbol (@user.outstanding_with_person_overall(@profile_owner) * -1) %></h4>
      <div class="mb-4 text-center">
        <h5 class="no-margin settle-up-button" data-id="<%= @profile_owner.id %>" data-name="<%= @profile_owner.first_name %>" data-amount="<%= humanized_money_with_symbol (@user.outstanding_with_person_overall(@profile_owner) * -1) %>">Settle All</h5>
      </div>
    <% elsif @user.outstanding_with_person_overall(@profile_owner) > 0 %>
      <h4 class="color-white">They owe you: <%= humanized_money_with_symbol @user.outstanding_with_person_overall(@profile_owner) %></h4>
      <!-- <div class="mb-4 text-center"> -->
        <!-- <h5 class="no-margin remind-button" data-id="<%= @profile_owner.id %>" data-name="<%= @profile_owner.first_name %>" data-amount="<%= humanized_money_with_symbol @user.outstanding_with_person_overall(@profile_owner) %>">Remind</h5> -->
      <!-- </div> -->
    <% else %>
      <h4 class="color-white">All Square</h4>
    <% end %>
  <% end %>
</div>

<div class="container">
  <div class="title-section">
    <h3>Overview</h3>
  </div>
  <div class="card">
    <div class="card-body text-center">
      <% if @balance == 0 %>
        <p class="mb-3">Across all groups, all square:</p>
        <h4 class="no-margin">£0.00</h4>
      <% elsif @balance > 0 %>
        <p class="mb-3">Across all groups, <%= @profile_owner.first_name %> is owed:</p>
        <h4 class="no-margin color-primary"><span class="color-primary"><%= humanized_money_with_symbol @balance %></span></h4>
      <% else %>
        <p class="mb-3">Across all groups, <%= @profile_owner.first_name %> owes:</p>
        <h4 class="no-margin color-danger"><span class="color-danger"><%= humanized_money_with_symbol (@balance * -1) %></span></h4>
      <% end %>
    </div>
  </div>
  <div class="card-row-space"></div>

  <div class="title-section">
    <h3>Ratings</h3>
  </div>
  <div class="card">
    <div class="card-body text-center">
      <p class="mb-3">Stinginess Ratio:</p>
      <h4 class="no-margin"><%= (@amount_lent.to_f/@amount_borrowed.to_f).round(2) %></h4>
      <p class="no-margin under-avatar-text">(higher is less stingy...)</p>
    </div>
  </div>
  <div class="card-row-space"></div>

  <div class="title-section">
    <h3>Profile Details</h3>
  </div>
  <div class="card">
    <div class="card-body">
      <p class="no-margin"><strong>Paypal:</strong> <%= @profile_owner.email %></p>
      <hr>
      <p class="no-margin"><strong>Joined On:</strong> <%= @profile_owner.created_at.strftime("%b %d, %Y") %></p>
    </div>
  </div>
  <div class="card-row-space"></div>
</div>

<!-- JAVASCRIPT FOR THE BUTTON TO SEND TO GROUP, TURN KITTY_CREATED=TRUE AND REDIRECT -->
<% content_for(:after_js) do %>
  <!-- Including the Facebook Extension SDK -->
  <script>
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.com/en_GB/messenger.Extensions.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'Messenger'));
  </script>

  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.1.1/sweetalert2.all.min.js' %>

  <script>
    settleUpButtons = document.querySelectorAll(".settle-up-button")
    settleUpButtons.forEach((button) => {
      button.addEventListener("click", () => {
        let settleWithId = button.dataset.id
        let settleWithName = button.dataset.name
        let settleWithAmount = button.dataset.amount
        let message = {
                      "attachment":{
                        "type":"template",
                        "payload":{
                          "template_type":"generic",
                          "elements": [{
                            "title":`<%= @user.first_name %> just settled all with ${settleWithName}`,
                            "subtitle": `Overall they settled ${settleWithAmount} across all shared Kittys.`,
                            "buttons":[{
                              "type":"web_url",
                              "url":"<%= ENV['NGROK'] %>",
                              "title":"View the Expense",
                              "webview_height_ratio": "full",
                              "webview_share_button": "hide",
                              "messenger_extensions": true
                            }]
                          }]
                        }
                      }
                    };
        swal({
                  title: "Confirmation",
                  text: `You have paid ${settleWithName} ${settleWithAmount}?`,
                  type: "warning",
                  showCancelButton: true,
                  confirmButtonColor: '#60D173',
                  confirmButtonText: 'Yes, I have!',
                  cancelButtonText: "No, cancel it!",
                  closeOnConfirm: false,
                  closeOnCancel: false
              }).then((result) => {
                                    if (result.value) {
                                      swal({
                                        title: 'Settled Up!',
                                        text: 'You are settled over all Kittys',
                                        type: 'success',
                                        confirmButtonColor: '#60D173',
                                        confirmButtonText: 'Ok!'
                                      }).then(() => {
                                        // Begin Facebook's Send to Group Flow
                                        MessengerExtensions.beginShareFlow(function(share_response) {
                                          if(share_response.is_sent){
                                            // The user actually did share.
                                            // Perhaps close the window w/ requestCloseBrowser().
                                            window.location.href = `<%= user_settle_all_path %>?settle_with_id=${settleWithId}`
                                          }
                                          else {
                                            window.location.href = `<%= user_settle_all_path %>?settle_with_id=${settleWithId}`
                                          }
                                        },
                                        function(errorCode, errorMessage) {
                                        // An error occurred in the process of sending message, do nothing
                                        },
                                        message,
                                        "broadcast");
                                      })
                                    } else if (result.dismiss === 'cancel') {
                                      swal({
                                        title: 'Cancelled!',
                                        text: "You haven't settled up just yet",
                                        type: 'error',
                                        confirmButtonColor: '#C4183C',
                                        confirmButtonText: 'Close'
                                      })
                                    }
                                  })
      })
    })
  </script>
<% end %>