config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # Defining root depending on whether logged in or not
  unauthenticated do
    root 'pages#home'
  end
  authenticated do
    root 'pages#call_facebook'
  end

  get '/redirect', to: 'pages#redirect', as: 'redirect'

  # GROUPS CONTROLLERS
  resources :groups, only: [:show, :update, :destroy]
  get '/new_kitty', to: 'groups#new_kitty', as: 'new_group'
  get '/reminder', to: 'groups#reminder', as: 'groups_reminder'

  # USERS CONTROLLERS
  resources :users, only: [:show]
  get '/transactions/:id', to: 'users#transactions', as: 'user_transactions'
  get '/friends/:id', to: 'users#friends', as: 'user_friends'
  get '/dashboard/:id', to: 'users#dashboard', as: 'user_dashboard'
  get '/settle_all', to: 'users#settle_all', as: 'user_settle_all'

  # EXPENSES CONTROLLERS
  resources :expenses, only: [:new, :create, :show]
  post '/expenses/upload', to: 'expenses#upload', as: 'expenses_upload'

  # WEBHOOKS CONTROLLER
  get 'webhooks', to: 'webhooks#messenger'
  post 'webhooks', to: 'webhooks#messenger_receive_message'

  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :create ]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_fixed_nav_btn.html.erb
<% unless @group.thread_type == "USER_TO_PAGE" %>
  <div class="container">
    <div class="floaty">
      <ul class="floaty-list">
        <li class="floaty-list-item floaty-list-item--blue">
          <%= link_to groups_reminder_path(@group) do %>
            <span class="floaty-list-item-label">Reminder</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" class="floaty-btn-icon floaty-btn-icon-non-main absolute-center">
                <path d="M22 5.72l-4.6-3.86-1.29 1.53 4.6 3.86 1.29-1.53zm-14.12-2.33l-1.28-1.53-4.6 3.85 1.29 1.53 4.59-3.85zm4.62 4.61h-1.5v6l4.75 2.85.75-1.23-4-2.37v-5.25zm-.5-4c-4.97 0-9 4.03-9 9s4.02 9 9 9c4.97 0 9-4.03 9-9s-4.03-9-9-9zm0 16c-3.87 0-7-3.13-7-7s3.13-7 7-7 7 3.13 7 7-3.13 7-7 7z" fill="#fff"/>
                <path d="M0 0h24v24h-24z" fill="none"/>
            </svg>
          <% end %>
        </li>
        <li class="floaty-list-item floaty-list-item--green">
          <%= link_to new_expense_path do %>
            <span class="floaty-list-item-label">Create or Settle</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="floaty-btn-icon floaty-btn-icon-non-main absolute-center">
                <path d="M3 17.25v3.75h3.75l11.06-11.06-3.75-3.75-11.06 11.06zm17.71-10.21c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z" fill="#fff"/>
                <path d="M0 0h24v24h-24z" fill="none"/>
            </svg>
          <% end %>
        </li>
      </ul>
      <div class="floaty-btn">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="floaty-btn-icon floaty-btn-icon-plus absolute-center">
            <path d="M19 6.41l-1.41-1.41-5.59 5.59-5.59-5.59-1.41 1.41 5.59 5.59-5.59 5.59 1.41 1.41 5.59-5.59 5.59 5.59 1.41-1.41-5.59-5.59z" fill="#fff"/>
            <path d="M0 0h24v24h-24z" fill="none"/>
        </svg>
      </div>
    </div>
  </div>



  <script>
    // FIXED NAV BUTTON SELECTOR
    let floatArea = document.querySelector(".floaty")
    let floatButton = document.querySelector(".floaty-btn")
    let floatList = document.querySelector(".floaty-list")
    floatArea.addEventListener("click", () => {
      console.log("I'm Clicked")
      floatArea.classList.toggle("is-active")
      floatButton.classList.toggle("active-rotate")
      floatList.classList.toggle("floaty-list-active")
    })
  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% unless @hidenav %>
  <nav class="navbar navbar-expand-lg navbar-dark navbar-background" id="navbar">
    <!-- Links directly in navbar -->
    <h3 class="navbar-brand no-margin h3-lighter" href="#"><%= @nav_title %></h3>
    <a class="navbar-toggler collapsed no-border no-padding" data-toggle="collapse" data-target="#navbarNavDropdown-1" aria-controls="navbarNavDropdown-1" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa fa-bars fa-lg color-white" id="burger-menu" aria-hidden="true"></i>
    </a>

  </nav>
  <!-- Menu that opens on burger touch -->
  <div class="hidden-menu" id="hidden-menu-1" style="">
    <div class="container">
      <ul class="navbar-nav mr-auto text-center">
        <%= link_to group_path(@group) do %>
          <li class="nav-item">
            <h4 class="color-white small-padding"><i class="fa fa-users fa-fw color-white mr-2" aria-hidden="true"></i>Current Group</h4>
          </li>
        <% end %>
        <%= link_to user_friends_path(@user) do %>
        <li class="nav-item">
          <h4 class="color-white small-padding"><i class="fa fa-group fa-fw color-white mr-2" aria-hidden="true"></i>Friends</h4>
        </li>
        <% end %>
        <%= link_to user_transactions_path(@user) do %>
          <li class="nav-item">
            <h4 class="color-white small-padding"><i class="fa fa-exchange fa-fw color-white mr-2" aria-hidden="true"></i>Transactions</h4>
          </li>
        <% end %>
        <%= link_to user_dashboard_path(@user) do %>
          <li class="nav-item">
            <h4 class="color-white small-padding"><i class="fa fa-dashboard fa-fw color-white mr-2" aria-hidden="true"></i>Dashboard</h4>
          </li>
        <% end %>
        <%= link_to user_path(@user) do %>
          <li class="nav-item">
            <h4 class="color-white small-padding"><i class="fa fa-user fa-fw color-white mr-2" aria-hidden="true"></i>Profile</h4>
          </li>
        <% end %>
        <!-- <li class="nav-item">
          <h4 class="color-white small-padding"><i class="fa fa-bug fa-fw color-white mr-2" aria-hidden="true"></i>Report a bug</h4>
        </li> -->
      </ul>
    </div>
  </div>

<% else %>

  <nav class="navbar navbar-expand-lg navbar-dark navbar-background">
    <h3 class="navbar-brand no-margin" href="#"><%= @nav_title %></h3>
    <i class="fa fa-bars fa-lg color-white" aria-hidden="true"></i>
  </nav>

<% end %>


<% content_for(:after_js) do %>
  <script>
  // BURGER MENU ANIMATION
  let navbar = document.querySelector("#navbar")
  let burger = document.querySelector("#burger-menu")
  let menu = document.querySelector("#hidden-menu-1")
  let content = document.querySelector("#content-container")
  burger.addEventListener("click", () => {
    burger.classList.toggle("navbar-toggler-icon-rotated")
    menu.classList.toggle("hidden-menu-show")
    content.classList.toggle("content-hide")
    navbar.classList.toggle("navbar-fixed")
  })
  </script>
<% end %>

app/views/shared/_tabs.html.erb
<!-- ##################################################################################################################### -->
<!-- Tabs Bar -->
<!-- ##################################################################################################################### -->
<div class="tab">
  <button class="tablinks" id="firsttab" onclick="openCity(event, 'FirstTab')"><%= @tabs[0] %></button>
  <% @tabs.each_with_index do |tab, index| %>
    <% if index != 0 %>
    <button class="tablinks" onclick="openCity(event, '<%= tab %>')"><%= tab %></button>
    <% end %>
  <% end %>
</div>

<% content_for(:after_js) do %>
  <script>
    const firstTab = document.getElementById("FirstTab");
    const firsttab = document.getElementById("firsttab")
    const tablinks = document.getElementsByClassName("tablinks");

    // Tabs Selector
    // Display first tab initially:
    firstTab.style.display = "block";
    firsttab.className += " active";
    // Change Navbar Title as Tabs Change
    tablinks[0].addEventListener("click", () => {
      // document.querySelector(".navbar-brand").innerHTML = "Add an expense"
    })
    tablinks[1].addEventListener("click", () => {
      // document.querySelector(".navbar-brand").innerHTML = "Settle an expense"
    })
    // Change Displayed Tab as Tabs Change
    function openCity(evt, cityName) {
      var i, tabcontent, tablinks;
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
          tabcontent[i].style.display = "none";
          tablinks = document.getElementsByClassName("tablinks");
      }
      for (i = 0; i < tablinks.length; i++) {
          tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      document.getElementById(cityName).style.display = "block";
      evt.currentTarget.className += " active";
    }
  </script>
<% end %>

app/views/shared/_wagon_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>